name: Continuous integration

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Ensure files are formatted with black
      run: |
        pip install --upgrade pip
        pip install black==19.10b0
        black --check ./examples
  docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Ensure the docker image works and can start.
      run: |
        docker build -t keras-io .
        docker run --rm -d -p 8000:8000 --name keras-io-server keras-io
        sleep 10
        docker exec keras-io-server echo I am alive
        docker kill keras-io-server
